name: extractor

channels:
  - conda-forge
  - pytorch
  - nvidia

dependencies:
  - python=3.8.17
  - cudatoolkit=11.8.0
  - pytorch=2.0.1
  - pip
  - pip:
      - numpy==1.22.0
      - pyqt5==5.15.9
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.12.2
      - qt-material==2.14
      - opencv-python==4.8.0.76
      - pillow==10.0.0
      - matplotlib==3.7.2
      - scikit-learn==1.3.0
      - torchvision==0.15.2
      - dface==1.1.5
      - tqdm==4.66.1
      - pyyaml==6.0.1
      - kneed==0.8.5
      - numexpr==2.8.5
      - tensorflow
